[#337] Automatically add junit-platform-launcher to testRuntimeOnly
... for JUnit Platform projects to avoid "UNKNOWN_ERROR" or:
"NoClassDefFoundError: org.junit.platform.launcher.core.LauncherFactory" with PIT 1.14.0+
(with pitest-junit-plugin 1.2.0+).

That dependency is no longer shaded. More details:
https://github.com/szpak/gradle-pitest-plugin/issues/337