Remove dependency on CharMatcher due to issues with Guava 22
While upgrading from Guava 21 to Guava 22, something broke in
CharMatcher. This is a requirement to upgrade to the Android
Gradle plugin 3.0.0.

The stack trace reads as follows:
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'java.util.function.Predicate$$Lambda$345/1043479128@55b1079' with class 'java.util.function.Predicate$$Lambda$345/1043479128' to class 'com.google.common.base.CharMatcher'
        at info.solidsoft.gradle.pitest.PitestPlugin.getMockableAndroidJarPath(PitestPlugin.groovy:208)
        at info.solidsoft.gradle.pitest.PitestPlugin$_apply_closure1.doCall(PitestPlugin.groovy:74)

As a workaround, the Pitest plugin no longer depend on CharMatcher,
and uses a regular expression instead.